#!/bin/bash
yay -S python python-pip 2>/dev/null || \
	sudo pacman -S python python-pip 2>/dev/null || \
	sudo apt install python3 python-pip 2>/dev/null || \
	apt install python3 python-pip 2>/dev/null

sudo pip install pathlib 2>/dev/null || \
	pip install pathlib

quitupAlias="alias quitup='python ../quitup.py'"
if [[ -f "$HOME/.zshrc" ]]; then
	echo "Found .zshrc"
	if ! [[ grep -Fxq "$quitupAlias" "$HOME/.zshrc" ]]; then
		echo $quitupAlias >> ~/.zshrc
	fi
elif [[ -f "$HOME/.bashrc" ]]; then
	echo "Found .bashrc"
	if ! [[ grep -Fxq "$quitupAlias" "$HOME/.bashrc" ]]; then
		echo $quitupAlias >> ~/.bashrc
	fi
else
	echo "No zshrc or bashrc file was found in the workspace"
fi
