#!/bin/bash
yay -S python python-pip 2>/dev/null || \
	sudo pacman -S python python-pip 2>/dev/null || \
	sudo apt install python3 python-pip 2>/dev/null || \
	apt install python3 python-pip 2>/dev/null

sudo pip install pathlib 2>/dev/null || \
	pip install pathlib

quitupAlias="alias quitup='python ../quitup.py'"
echo $quitupAlias >> ~/.zshrc || \
	echo $quitupAlias >> ~/.bashrc || \
	echo "No zshrc or bashrc file was found in the workspace"
